class Outcome
  TYPES: Array[Symbol]

  @body: Symbol | nil
  @item_to_give: Item | nil
  @tag_to_give: String | nil
  @type: String | nil

  def die: -> untyped

  def give: (Item weapon) -> untyped

  def give_item: (Item item) -> untyped

  def give_tag: -> untyped

  def to_hash: -> Hash[Symbol, untyped]

  def transfer_to_event: (Symbol event) -> untyped

  def transfer_to_location: (Symbol location) -> untyped

  def validate: -> untyped
end
